name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue in the Rumble-LoL-Plugin project!"
        pr-message: "Thank you for make your first contribution to the Rumble-LoL-Plugin project!"
